package com.redhat.wsdl.addleadservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-04-17T12:45:48.806-04:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://redhat.com/wsdl/AddLeadService/", name = "AddLeadService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AddLeadService {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://redhat.com/wsdl/AddLeadService/", partName = "return")
    public LeadInfo addLead(
        @WebParam(partName = "first_name", name = "first_name")
        java.lang.String firstName,
        @WebParam(partName = "last_name", name = "last_name")
        java.lang.String lastName,
        @WebParam(partName = "company", name = "company")
        java.lang.String company,
        @WebParam(partName = "source", name = "source")
        java.lang.String source,
        @WebParam(partName = "phone", name = "phone")
        java.lang.String phone,
        @WebParam(partName = "email", name = "email")
        java.lang.String email,
        @WebParam(partName = "status", name = "status")
        java.lang.String status,
        @WebParam(partName = "rating", name = "rating")
        java.lang.String rating
    );
}
